name: CI
on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3 --base=origin/develop --head=${{ github.event.pull_request.head.sha }}
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage --base=origin/develop --head=${{ github.event.pull_request.head.sha }}
      - run: npx nx affected --target=build --parallel=3 --base=origin/develop --head=${{ github.event.pull_request.head.sha }}
